#ifndef CARDINAL_DIRECTIONS_H
#define CARDINAL_DIRECTIONS_H

typedef enum
{
    CARDINAL_DIRECTION_NORTH = 0,
    CARDINAL_DIRECTION_EAST = 1,
    CARDINAL_DIRECTION_SOUTH = 2,
    CARDINAL_DIRECTION_WEST = 3
} CardinalDirection;

#endif
